
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It's generated by Next.js and is required for TypeScript support in Next.js
